### ISSUE TITLE
Size it adds

### ISSUE THREAD

**Issue by mpjraaij** [lupas/nuxt-fire#17]
Hi there,

I did some investigating today and nuxt fire adds 421 KiB to the project with using 'auth', 'functions', 'storage' and 'realtimeDb'

Is there a way to minimize these added KiBs?

Thanks so much,
Maarten

**Comment by lupas** [comment]
Hi @mpjraaij 

Thank you for investigating that, that is quite big I agree.

Unfortunately, the Firestore modules themselves are very big, there's for example this issue on the official Github repo [here](https://github.com/firebase/firebase-js-sdk/issues/332) for that.

Fire-nuxt merely imports, configures & adds the chosen firebase modules to the global context. If you would do that manually, like described [here](https://medium.com/@pascalluther/nuxt-js-v2-firestore-ssr-938d8fb7d2b0), the same size issue would be the case (as far as I can judge).

I'm no expert when it comes to that, but I see two options on how to reduce it in Fire-nuxt:

1. Instead of adding each **module** to the global context, export each module so it can be imported in each .js/.vue file if needed
2. Export **each function** individually, so it can be imported individually like so:
`(import { sendVerificationEmail, reauthenticateWithCredential, ... } from 'firebase/auth';`

For 1) that would probably be doable, but then we could build it so people could decide with a flag `addGlobally` whether they wanted the modules to be available globally or not. I tend to use Firebase almost anywhere anyway, so I'm not sure if that would make a big difference. But that would also make fire-nuxt less inconvenient.

For 2) I think that would blow the whole thing, since this module is meant to make integration easier. Fire-nuxt itself would grow a lot by that and would have to be constantly updated along with the Firebase SDK, so I don't see that happening. But yeah, that would have the greatest impact to reduce file size.

For now I think I'll leave it like this, since the goal of nuxt-fire is to make integration easier, and these 2 options would make it more complicated again. If anyone finds a good solution to reduce nuxt-fire's file size without making it less convenient, be my guest and create a PR or let me know down below. Thx :)

**Comment by MarvinMiles** [comment]
Hi @lupas 
It is possible something [like this](https://davidea.st/articles/firebase-bundle-size) with nuxt? I can't find any info about web workers in nuxt

**Comment by lupas** [comment]
@MarvinMiles 
Thanks for linking the article, that indeed sounds interesting. So far I have little to no experience with web workers, so its currently hard for me to judge if that would not add too much complexity to this module, which so far is really quite a simple one. Also not sure if everyone would be happy if we rely on web workers in general.

If I get to it I will have a look at it, would be great if nuxt-fire could actually help to reduce bundle-size of firebase integration.

**Comment by lupas** [comment]
Closed, since nuxt-fire merely imports the firebase modules. With the useOnly option we already have an option in place to only use the needed modules. Everything else seems to be out of scope for nuxt-fire and would make this module less simple to use.

**Comment by lupas** [comment]
With PR https://github.com/lupas/nuxt-fire/pull/43 we added support for code spliiting via dynamic import().
