### ISSUE TITLE
EmailAuthProvider undefined

### ISSUE THREAD

**Issue by grahappa** [lupas/nuxt-fire#20]
I'm trying to `reauthenticateAndRetrieveDataWithCredential` in a flow that is allowing the user to update their email address like this;

**Re-authenticate a user**
https://firebase.google.com/docs/auth/web/manage-users#re_authenticate_a_user

However, how to get the credential is missing.  This seems to be a popular answer.

**How to create “credential” object needed by Firebase web user.reauthenticate() method?**
https://stackoverflow.com/questions/37811684/how-to-create-credential-object-needed-by-firebase-web-user-reauthenticate-m#37812541

`let credential = this.$fireAuth.EmailAuthProvider.credential("user@example.com", "password1234");`

> app.js:5350 Uncaught (in promise) TypeError: Cannot read property 'getCredential' of undefined

I noticed another issue

**Provide Shortcut to AuthProviders & other Utils**
https://github.com/lupas/nuxt-fire/issues/10

which states;

> Below "util" functions are not yet accessible via nuxt-fire, so one has to import import firebase from 'firebase/app' manually where needed.
> 
> ....
> 
> and probably many more...

I wondering if `EmailAuthProvider` is one of those "util" functions that are not yet accessible and if so how to make it so that it is?

thank you

**Comment by lupas** [comment]
Hi @grahappa 

As you've seen correctly, #10 is already addressing what you are experiencing. Currently you have to solve it the following way to achieve what you want:

```js
import firebase from 'firebase/app'

firebase.auth.EmailAuthProvider...
```

This should work for you, please try that out.

As you can see, we access the **auth object** above and not the **auth() instance** (hope that is the correct terminology), which is what is created with fireAuth like so:
```js
import firebase from 'firebase/app'
import 'firebase/auth'

const fireAuth = firebase.auth()
```

So the module is working correctly, since even if you don't use the module you wont be able to access EmailAuthProvider from the auth() instance:
```js

import firebase from 'firebase/app'
import 'firebase/auth'

const fireAuth = firebase.auth()
// NOT going to work
fireAuth.EmailAuthProvider...

// GOING going to work
firebase.auth.EmailAuthProvider...
```

What #10 is talking about is making firebase accessible as $fireBase via the module directly, without the need to import firebase, but that would be pretty much the same as just adding `import firebase from 'firebase/app'` to where you actually need to do that with the exception to that the module is available globally. So as of now there is not much benefit to it - but it is still open as an issue in case many people would actually prefer it that way.

Hope that makes any sense, otherwise please let me know :)

**Comment by lupas** [comment]
The out providers can now be accessed via $firebaseAuthObj, see #24 .

 this.$fireAuthObj.EmailAuthProvider

**Comment by shal3v-office** [comment]
today the access is:
this.$fireModule.auth.EmailAuthProvider
