### ISSUE TITLE
How to use this in middleware?

### ISSUE THREAD

**Issue by saikksub** [lupas/nuxt-fire#28]
I am trying to use middleware router for authentication guards. Is it possible to use this inside Nuxt middleware?

**Comment by lupas** [comment]
@saikksub 

If you refer to **[client side middleware](https://nuxtjs.org/api/pages-middleware/)**, yes, you can access it like so:

```js
export default function({ app }) {
  const fireAuth = app.$fireAuth)
 // ... and so on
}
```

**Important:** fireAuth should be wrapped in `if (process.browser) {...}` because Firebase Authentication does only work client-side in general!

If you are talking about **[server middleware](https://nuxtjs.org/api/configuration-servermiddleware/)** - it is currently not possible. In that case, please refer to #9 and describe your usecase in more detail there,
