### ISSUE TITLE
Do you have any tutorial on Deploying Nuxt app to Firebase?

### ISSUE THREAD

**Issue by just10minutes** [lupas/nuxt-fire#35]
@lupas This is not a bug. Didn't know where to ask so asking here.

Do you have any Nuxt 2 SSR projects hosted on Firebase?

I am struggling from last 48 hours :( Tried many tutorials and videos and blog posts. all are outdated I believe. so just trying my luck here

Thanks you

**Comment by lupas** [comment]
@just10minutes

Depends with what you mean by "on Firebase" and what you want to achieve.

You need to be aware that there are different ways to deploy an application on Firebase.

I personally prefer to use the nuxt generate to pre-render all content and deploy a static version of my site after every major change. This is technically not SSR, but pre-rendering - which can again happen on server side or on client side.

**1) Deploy as static site on _Firebase Hosting_**
Example Projects:
https://github.com/lupas/nuxt-fire-demo 
 
Note: I prefer Netlify for this purpose since it can do the rendering server-side straight from e.g. GitHub.

**2) Deploy SSR application to _Firebase Functions_ to automatically generate static content that gets hosted on Firebase Hosting after every change**
Example: http://github.com/davidroyer/nuxt-ssr-firebase
Seems a bit tricky and only outdated examples available. No experience here, cannot help you there. Seems very interesting, but I would not go this approach if you are struggling to understand it.

3) Deploy the entire node SSR application to a Webserver to truly serve the application with SSR
Currently not supported on Firebase, but can e.g. be achieved by using Google App Engine which can be connected to a Firebase Project:
Guide:
https://medium.com/@pascalluther/deploying-a-nuxt-js-v2-app-to-google-app-engine-google-cloud-platform-69c9008531bc
Example:
https://github.com/lupas/nuxt2-appengine

Depending on your project, but I would rather opt for Heroku in this case.

Hope that helped a bit. Let me know which way you want to go so I might be able to help you more.

**Comment by just10minutes** [comment]
@Lucas Thank you very much for such detailed explanation.

The website which I am trying to build is a Recipe Blog for my friend. Currently it is hosted as wordpress website. Which is too much bloated now so planning for better using Nuxt.

Website doesn't have much traffic so looking for free tier options.

1. I have around 300 posts right now, pre-rendering them everytme there is a new post (probably once in a day or two days). is it something advisable? There is no much need of live feed apart from comments section but that also can wait. but pre-rendering all pages is something may not be feasible with this.

2. Yes you are right, and there is no much help out there.

3. Involves cost so trying to avoid this. I need to keep the instance 24/7 running as my friend might want post recipes any time of the day so application need to be online.

I just hope David updates his repo with latest nuxt-ssr demo.

Once again thank you very much. you are too good with your explanations.

**Comment by lupas** [comment]
@just10minutes

Checkout www.netlify.com .

1. Yes, since blogposts are not changed or added very frequently, I would advise you to think about pre-rendering. Everytime a blogpost changes or you add a blogpost, you can trigger a build (e.g. via netlify API) and the whole page gets statically generated again. This makes your website load fast as a breeze because it is just a static file without any other dynamic calls to be made.

You can use Nuxt's <client-only/> (before <no-ssr/> for the dynamic parts (e.g. comments), then these will only be loaded on client side. Then these won't be necessarily reflected in SEO (though Google seems to be changing that, so they might).

2. Yep. I might look into it at some point.

3. Yep. Dynamic web-servers usually cost much more than static website. One more reason to use pre-rendering.

**Comment by just10minutes** [comment]
@lupas Thank you once again for the explanation.

1. AM I correct in saying I have to pre build all posts even though there is only one new post added? I will definitely check how much time it's gonna take to build around 300 posts.

1.1  Didn't quite get here. Where will the comments be stored? It's fine if comments are not considered for SEO. I am not expecting link back comments so it's fine to ignore. If I get this portion right probably I can host website on Netlify using the Starter pack which is Free.


2. One of my online mentor like you(Name Niclas) suggested Google Cloud Run `https://www.youtube.com/watch?v=3OP-q55hOUI`  a new server less feature which allows for hosting of Nuxt apps, it's easy but the concern is I am still thinking how much it might cost me to have around 10000 unique viewers for my site.

3.  yes I am looking for fast rendering of pages.  If i get my comments section right probably I will stick to Pre rendering ,  I will create some normal front end to store data at the backend so my friend can post his blogs which will be linked to Netlify API. Hope my thinking is correct.

Thank you once again for your suggestions, These kind of suggestions actually save a lot of time and I also assist few others who asks me same questions :)

**Comment by lupas** [comment]
1. Not necessarily, but if you want to keep it simple, yes. 300 posts is not that much tbh, that should not be a problem at all. Especially since Netlify won't cost you anything.

1.1 Depends on how your comments backend looks like. If you use a service like disqus then they will live there. If you build your own you of course have to have a server for that where you would store the commets. Or you could go "server-less" and use Firebase Firestore to store & retrieve the comments. You could also store your blogpost there. Free tier will probably be enough for your needs.

2. I haven't heard from Googles Cloud Run yet, but I'll have a look at it, sounds interesting. Let me know if you end up trying it out, would be interested.

3. Yep, use Netlify and then e.g. use a Firebase "serverless-backend" where you store & retrieve the comments, blogposts and so on. That should do the trick :)

And don't mention it, just help someone else in the future, it's give and take 👍

**Comment by just10minutes** [comment]
Yes I do that, I am more than happy to share knowledge if I know about it. Sharing is caring.

One more question came up now - With pre-rendering can i have free text searching on the website? what is your thought on this?

Anyway with my current architecture - Firestore as backend I do not have Free text searching out of the box. So if pre-rendered thing can have it that will be booster to think pre-rendering :) rather than depending on Elastic search for this feature.

**Comment by just10minutes** [comment]
Never Mind I see this repo https://github.com/nuxt-community/lunr-module  will let you know once i try out this. Still far ahead :)

**Comment by lupas** [comment]
I'm not too familiar with text searching myself, haven't worked much with it. But should not make a big different if it is pre-rendered or not. As long as your data is accessible in a backend like Firebase you should also be able to query it with text-search.

Maybe checkout Algolia? They have a free tier as long as your project is not commercial.

But here I can't help you much unfortunately.

**Comment by just10minutes** [comment]
No problem I undertand.

 Algolia Free Tier is kind of tricky because website might have ad-sense, so not sure how alogolia treats it. Will it consider as Commercial or personal site. So do not want to get in to such things.

**Comment by ShaggyTech** [comment]
Just wanted to leave a comment regarding David Royer’s repo and hosting on Firebase functions/hosting with Nuxt.  

I’m just stumbling through this but I’ve managed to get it to work pretty seamlessly.  It’s basically a PWA with SSR handoff in the event that the static file(s) aren’t available on the hosting server, it will ask the firebase http function to provide them.  It’s still a proof of concept and I’m improving it daily.  The nuxt rendering from the server is currently broken as I don’t fully understand how that is supposed to work but I’m getting there.   Make sure you’re in the ‘pwa-poc’ branch before you try and install/build.   

https://github.com/ShaggyTech/nuxt2-ssr-firebase/tree/pwa-poc?files=1

**Comment by mustafa-kahraman** [comment]
I found this article and its works.
you just need some changes...
https://medium.com/likecoin/quick-nuxt-js-ssr-prototyping-with-firebase-cloud-functions-5277553610a8

**Comment by rajesh-h** [comment]
@lupas if possible can you please guide me what will be my best option for below scenario.

Dev Environment Local Machine:

> Nuxt SSR Mode
> Nuxt/Content - using each article as json document inside content folder
> Static generation using nuxt export
> uploading the dist folder to firebase hosting.


My Articles data or new posts gets added to firstore on a daily basis so every day I want to setup below flow. Every day I have to do this on my local machine right now.

> I download new articles from firestore into my content folder inside nuxt source code
> I run yarn generate to regenerate all static files
> upload to firebase hosting

I would like to automate the daily task using serverless way. what I should be doing to achieve this? I can use cloud functions to fetch the latest Articles but I am not sure where I should store these articles.  What service I can use to run the yarn generate command?

Your input will be much appreciated.
