### ISSUE TITLE
Show an example how to do auth in universal mode

### ISSUE THREAD

**Issue by thebspin** [lupas/nuxt-fire#68]
I've tried reading some issue's and overal nuxt articles but am i right saying that you currently cant auth your user when using ssr (univeral mode) on the server? I don't want anyone to get access to certain parts of my website unless they are authed.. doing this clientside seems to me you would be able to fake being logged in?

**Comment by lupas** [comment]
Hey @thebspin 

If you store your protected data in **Firestore or RealtimeDb** and protect them properly with **security rules**, no one can fake access to that data without being properly authenticated, even on Nuxt Universal mode (just don't access that specific data from the server side). I In that case you would only load protected data from client-side after the user has been authenticated, and everything else is statically rendered on server side.

If you want to protect **static content** that is **rendered on server-side** and doesn't come from a Firebase service, users could potentially fake being logged in and see that content, depending on how you protect your server otherwise. I don't see many reasons of doing this while using Firebase (Auth) though, after all Firebase is a serverless service and trying to implement server-side authentication without using its other services kind of defeats that purpose, doesn't it? There's other ways without using Firebase to authenticate in such scenario that work better in SSR.

So maybe ask yourself what exactly you want to achieve? Maybe there's an easier way than implementing server-side authentication with Firebase? E.g. just storing your protected data in Firestore instead?

I created the issue #69 to track this, since many people seem to want to achieve server-side render Firebase Auth protected content. Maybe eventually we'll find a good solution and can implement this in nuxt-fire.
