### ISSUE TITLE
Nuxt Generate finished but did not exit

### ISSUE THREAD

**Issue by ngblaylock** [lupas/nuxt-fire#90]
This may not be an issue, but might be more of a question. When I run `npm run generate` I get the following error:
```
⚠ Nuxt Warning 

The command 'nuxt generate' finished but did not exit after 5s
This is most likely not caused by a bug in Nuxt.js
Make sure to cleanup all timers and listeners you or your plugins/modules start.
Nuxt.js will now force exit

DeprecationWarning: Starting with Nuxt version 3 this will be a fatal error  
```
I am not using Vuex, but I am using the `onSnapshot` method, which is what I have narrowed the issue down to. It appears that the `onSnapshot` method uses a listener which is causing the error. So I looked at the firebase docs and read the following - [link](https://firebase.google.com/docs/firestore/query-data/listen#detach_a_listener):
```
var unsubscribe = db.collection("cities")
    .onSnapshot(function (){
      // Respond to data
      // ...
    });

// Later ...

// Stop listening to changes
unsubscribe();
``` 
So I tried to save the snapshot to something like `this.destroySnapshot`, then in the `beforeDestroy` lifecycle hook, call `this.destroySnapshot()`. However, when I run `npm run generate` again, it still gives me the same error.

So my real question is, is this an issue with Nuxt, Firebase, or me being a total noob? I am specifically worried about the line saying `Starting with Nuxt version 3 this will be a fatal error`

If you want to see my code, it is in my [nuxt-sandbox](https://github.com/ngblaylock/nuxt-sandbox/blob/master/pages/firebase/firestore.vue) repo.

And more than anything, thank you for creating Nuxt-Fire.

**Comment by lxsedov** [comment]
same here

**Comment by lupas** [comment]
Hey guys.
I don't think this has anything to do with nuxt-fire as a module itself, but Firebase+Nuxt in general.

It seems as if the routes get generated correctly and everything works as it should, but the error message gets generated since some recent Nuxt 2.x version. 

I managed to reproduce the issue like so in a brand new project without nuxt-fire in the firebaseInit.js Plugin:
```js
// firebaseInit.js Plugin

import firebase from 'firebase/app'
import 'firebase/database'

const firebaseConfig = {
// Config
}

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig)
}

export const fireDb = firebase.database() // --> This alone throws the error mesage.
```

Seems to be an issue with initialising RealtimeDb in a nuxt-plugin.

@ngblaylock @lxsedov
Do you use RealtimeDb or do you get the error even with RealtimeDb disabled?

**Similar Issues**
https://stackoverflow.com/questions/60124687/nuxt-generate-routes-by-firebase-data-is-finished-but-did-not-exit-after-5s

**Comment by lupas** [comment]
Okay, so I found this [here](https://stackoverflow.com/questions/38279329/how-firebase-listener-actually-work):
```js
When your app connects to the Firebase Database, it opens a web socket connection from the device to a Firebase server. This connection stays open for the lifetime of your app or until you call goOffline().
```

So when I do the following in the plugin above:
```js
// firebaseInit.js Plugin

import firebase from 'firebase/app'
import 'firebase/database'

const firebaseConfig = {
// Config
}

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig)
}

export const fireDb = firebase.database() // --> This alone throws the error mesage.

fireDb.goOffline() // <-- ADD THIS LINE
```
Then the warning goes away.

So I guess we need to find a way to disconnect from the RealtimeDatabase when `nuxt generate` is finished.

**Comment by lupas** [comment]
Okay, in the example above (NOT using nuxt-fire) I can disconnect the RealtimeDatabase like so in nuxt.config.js:

```js
// nuxt.config.js
import { fireDb } from './plugins/firebaseInit.js'

export default {
  hooks: {
    generate: {
      done() {
        // disconnect RealtimeDatabase after nuxt generate
        fireDb.goOffline()
      }
    }
  },
```

Only thing left now is to implement this in nuxt-fire be setting this hook within the module, I'll have a look at it soon.

**Comment by lupas** [comment]
## Issue (2) (Firestore .onSnapshot)
@ngblaylock

Call .onSnapshot in `mounted()` instead of `created()` hook, that should solve the issue. This way the listener is not called twice on server and on client.

If you want to get initial data on SSR generate already, do a regular get() in the created() hook.

**Comment by lxsedov** [comment]
thanks! can confirm .goOffline() works for Firebase Database

**Comment by ngblaylock** [comment]
Thanks @lupas. I can't believe I didn't try that, but it works perfectly. Apparently I don't know as much about the lifecycle hooks as I thought I did. I appreciate you looking into this for me, and hope it helps the rest of the community.

**Comment by krisism** [comment]
If looking for a similar solution with Firestore, you can use firedb.terminate() instead of 'goOffline()' in the nuxt.config.js hook mentioned above =)  (Thanks for this thread, helped me a lot!)

**Comment by lupas** [comment]
@krisism 
Awesome, I was actually looking for that since the issue is also there with Firestore. Thanks for the tip!

Still trying to find a way to call this in the generate.done hook though since this$fireStore is not accessible there.. 

https://github.com/nuxt-community/firebase-module/issues/93 is open for trying to fix this within this module.

**Comment by simeon9696** [comment]
> If looking for a similar solution with Firestore, you can use firedb.terminate() instead of 'goOffline()' in the nuxt.config.js hook mentioned above =) (Thanks for this thread, helped me a lot!)

I added the code as you suggested because I had the same error, then it fully crashed because 'it was already terminated'. Not sure what's happening there

**Comment by dmvvilela** [comment]
For those who still did not manage to fix this, nuxt firebase module has a config flag to terminate thing on generate:
terminateDatabasesAfterGenerate: true

View doc here: https://firebase.nuxtjs.org/guide/options/
